### ISSUE TITLE
Document topics to pass values to nodes

### ISSUE THREAD

**Issue by freaktechnik** [Ekristoffe/node-red-contrib-wellness#1]
The only way to find out how to provide the values to the nodes is to look at the source code currently.

**Comment by Ekristoffe** [comment]
Indeed ... I have totally forgot about this miss.
Do you have any idea of example on how to explain it the best possible ?

**Comment by freaktechnik** [comment]
I would expect it to be in the documentation of the individual nodes, but maybe adding it to the readme might be useful too?

**Comment by Ekristoffe** [comment]
I quickly made this, what do you think ? anything should be changed ?
![image](https://user-images.githubusercontent.com/5562219/126861517-3b81723b-5705-423e-98b1-dccb19cacd9e.png)

**Comment by freaktechnik** [comment]
Looks great!

**Comment by Ekristoffe** [comment]
I just updated it on Github, NPM and Node-red repo, I hope it will help.
If you have any comment, please share them.

**Comment by freaktechnik** [comment]
Thanks!
